// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/api/artwork.ts";
import * as $4 from "./routes/artist/[username].tsx";
import * as $5 from "./routes/greet/[name].tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/piece/[id]/index.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/api/artwork.ts": $3,
    "./routes/artist/[username].tsx": $4,
    "./routes/greet/[name].tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/piece/[id]/index.tsx": $7,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
