// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/admin/index.tsx";
import * as $4 from "./routes/api/artwork.ts";
import * as $5 from "./routes/artist/[username].tsx";
import * as $6 from "./routes/blog/[slug].tsx";
import * as $7 from "./routes/feed.ts";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/piece/[id]/index.tsx";
import * as $10 from "./routes/piece/[id]/like.ts";
import * as $11 from "./routes/piece/[id]/og.ts";
import * as $$0 from "./islands/ArtworkItem.tsx";
import * as $$1 from "./islands/Gallery.tsx";
import * as $$2 from "./islands/ReactionButton.tsx";
import * as $$3 from "./islands/ShareButton.tsx";
import * as $$4 from "./islands/UserList.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/admin/index.tsx": $3,
    "./routes/api/artwork.ts": $4,
    "./routes/artist/[username].tsx": $5,
    "./routes/blog/[slug].tsx": $6,
    "./routes/feed.ts": $7,
    "./routes/index.tsx": $8,
    "./routes/piece/[id]/index.tsx": $9,
    "./routes/piece/[id]/like.ts": $10,
    "./routes/piece/[id]/og.ts": $11,
  },
  islands: {
    "./islands/ArtworkItem.tsx": $$0,
    "./islands/Gallery.tsx": $$1,
    "./islands/ReactionButton.tsx": $$2,
    "./islands/ShareButton.tsx": $$3,
    "./islands/UserList.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
